### ISSUE TITLE
Odd flow behavior

### ISSUE THREAD

**Issue by johnkorzhuk** [flowtype/flow-for-vscode#121]
Flow is working for me, but I noticed it sometimes is slow. In the output I see the follow:
```
[2017-04-25T13:02:38.227Z] [ERROR] flow - Unknown return code from Flow: 10
[2017-04-25T13:02:38.227Z] [INFO] flow - [unknown]: Flow server in /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts
[2017-04-25T13:02:38.227Z] [ERROR] flow - Flow failed: /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts/node_modules/.bin/flow coverage --json extension-output-#3. Error: {"exitCode":10,"stderr":"File not found: /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts/extension-output-#3\n","stdout":""}
[2017-04-25T13:02:38.608Z] [ERROR] flow - Unknown return code from Flow: 10
[2017-04-25T13:02:38.609Z] [ERROR] flow - Flow failed: /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts/node_modules/.bin/flow coverage --json extension-output-#3. Error: {"exitCode":10,"stderr":"File not found: /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts/extension-output-#3\n","stdout":""}
[2017-04-25T13:02:38.698Z] [INFO] flow - [ready]: Flow server in /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts
[2017-04-25T13:05:04.244Z] [INFO] flow - Path to Flow: /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts/node_modules/.bin/flow
```

The relevant bit seems to be `"exitCode":10,"stderr":"File not found: /Users/johnkorz/Documents/prac/redux/udemy-sg/blog-posts/extension-output-#3\n","stdout":""}` but I'm not too sure what that means.

**Comment by NickMalt** [comment]
Same issue

**Comment by svipben** [comment]
Same here.

```
[2017-04-30T18:42:01.180Z] [INFO] flow - Path to Flow: /home/svipben/Documents/react-boilerplate/node_modules/.bin/flow
[2017-04-30T18:42:01.439Z] [INFO] flow - [unknown]: Flow server in /home/svipben/Documents/react-boilerplate
[2017-04-30T18:42:01.939Z] [INFO] flow - [ready]: Flow server in /home/svipben/Documents/react-boilerplate
[2017-04-30T18:42:02.136Z] [ERROR] flow - Unknown return code from Flow: 110
[2017-04-30T18:42:02.137Z] [INFO] flow - [unknown]: Flow server in /home/svipben/Documents/react-boilerplate
[2017-04-30T18:42:02.143Z] [ERROR] flow - Flow failed: /home/svipben/Documents/react-boilerplate/node_modules/.bin/flow status --json /home/svipben/Documents/react-boilerplate/configs/webpack.config.prod.js. Error: {"exitCode":110,"stderr":"Unhandled exception: End_of_file\n","stdout":""}
[2017-04-30T18:42:02.145Z] [ERROR] flow - Invalid JSON result from flow status --json /home/svipben/Documents/react-boilerplate/configs/webpack.config.prod.js. JSON:
''.
[2017-04-30T18:42:02.562Z] [INFO] flow - [ready]: Flow server in /home/svipben/Documents/react-boilerplate
[2017-04-30T18:42:05.539Z] [ERROR] flow - Unknown return code from Flow: 110
[2017-04-30T18:42:05.542Z] [INFO] flow - [unknown]: Flow server in /home/svipben/Documents/react-boilerplate
[2017-04-30T18:42:05.571Z] [INFO] flow - Path to Flow: /home/svipben/Documents/react-boilerplate/node_modules/.bin/flow
[2017-04-30T18:42:05.571Z] [ERROR] flow - Flow failed: /home/svipben/Documents/react-boilerplate/node_modules/.bin/flow status --json /home/svipben/Documents/react-boilerplate/configs/webpack.config.prod.js. Error: {"exitCode":110,"stderr":"Unhandled exception: End_of_file\n","stdout":""}
[2017-04-30T18:42:05.572Z] [ERROR] flow - Invalid JSON result from flow status --json /home/svipben/Documents/react-boilerplate/configs/webpack.config.prod.js. JSON:
''.
[2017-04-30T18:42:05.927Z] [INFO] flow - [ready]: Flow server in /home/svipben/Documents/react-boilerplate
```

**Comment by svipben** [comment]
```
extensionHost.ts:284[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'nameOrSourceURL' of undefinedd.logExtensionHostMessage @ extensionHost.ts:284
extensionHost.ts:284[Extension Host] TypeError: Cannot read property 'nameOrSourceURL' of undefined
    at CallSiteGetEvalOrigin (native)
    at /home/svipben/.vscode/extensions/flowtype.flow-for-vscode-0.6.0/build/pkg/nuclide-logging/lib/stacktrace.js:100:25
    at Array.map (native)
    at structuredStackTraceHook (/home/svipben/.vscode/extensions/flowtype.flow-for-vscode-0.6.0/build/pkg/nuclide-logging/lib/stacktrace.js:93:29)
    at Function.nuclideHookedPrepareStackTrace (/home/svipben/.vscode/extensions/flowtype.flow-for-vscode-0.6.0/build/pkg/nuclide-logging/lib/stacktrace.js:84:5)
    at TypeError.get stack [as stack] (native)
    at Object.u [as transformErrorForSerialization] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:13659)
    at e.unexpectedErrorHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:382376)
    at e.onUnexpectedError (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:15056)
    at Object.i [as onUnexpectedError] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:13431)d.logExtensionHostMessage @ extensionHost.ts:284
shell.ts:475Cannot read property 'nameOrSourceURL' of undefined: TypeError: Cannot read property 'nameOrSourceURL' of undefined
    at CallSiteGetEvalOrigin (native)
    at /home/svipben/.vscode/extensions/flowtype.flow-for-vscode-0.6.0/build/pkg/nuclide-logging/lib/stacktrace.js:100:25
    at Array.map (native)
    at structuredStackTraceHook (/home/svipben/.vscode/extensions/flowtype.flow-for-vscode-0.6.0/build/pkg/nuclide-logging/lib/stacktrace.js:93:29)
    at Function.nuclideHookedPrepareStackTrace (/home/svipben/.vscode/extensions/flowtype.flow-for-vscode-0.6.0/build/pkg/nuclide-logging/lib/stacktrace.js:84:5)
    at TypeError.get stack [as stack] (native)
    at Object.u [as transformErrorForSerialization] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:13659)
    at e.unexpectedErrorHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:382376)
    at e.onUnexpectedError (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:15056)
    at Object.i [as onUnexpectedError] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:13431)
```

**Comment by foobar8675** [comment]
Same here. Is there a workaround for this?

**Comment by f0und3r** [comment]
Same

**Comment by peterschussheim** [comment]
I am receiving the same `Unknown return code from Flow: 10` using latest extension and vscode insiders build.

**Comment by eps1lon** [comment]
Solved this issue for me by deleting the flow-typed directory. Running `flow-typed install` afterwards caused no problems. Happened twice now already.
