### ISSUE TITLE
(Bug?) Activating extension `flowtype.flow-for-vscode` failed: Cannot find module 'rxjs'.

### ISSUE THREAD

**Issue by mreishus** [flowtype/flow-for-vscode#185]
## Summary:
I'm not able to get the extension to load.  Checking the vscode dev tools, I see this error in the console:
Activating extension `flowtype.flow-for-vscode` failed: Cannot find module 'rxjs'.

## Stack trace:
```
console.ts:123 [Extension Host] Activating extension `flowtype.flow-for-vscode` failed:  Cannot find module 'rxjs'
t.log @ console.ts:123
console.ts:123 [Extension Host] Here is the error stack:  Error: Cannot find module 'rxjs'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:498891)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\redacted\.vscode\extensions\flowtype.flow-for-vscode-0.7.2\build\pkg\commons-node\stream.js:38:13)
	at Object.<anonymous> (C:\Users\redacted\.vscode\extensions\flowtype.flow-for-vscode-0.7.2\build\pkg\commons-node\stream.js:305:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
extensionService.ts:437 Activating extension `flowtype.flow-for-vscode` failed: Cannot find module 'rxjs'.
```

## Versions:
```
VSCode 1.18.0
flowtype.flow-for-vscode 0.7.2
I'm using   "flow.useNPMPackagedFlow": true
flow-bin 0.59.0 is in my package.json / node_modules
```

## Other

I do have rxjs in my project, and I have third party definitions loaded in .\flow-typed\npm\ from flow-typed.

I am using 'open folder' to open the same folder that has my package.json and node_modules inside of it.

Running 'yarn flow' from the command line does work.

**Comment by mreishus** [comment]
I uninstalled and reinstalled the extension and the error went away.
