### ISSUE TITLE
[BUG] Activating extension `flowtype.flow-for-vscode` failed

### ISSUE THREAD

**Issue by trjstewart** [flowtype/flow-for-vscode#198]
## Summary
Extension fails to load in Insiders build on Windows system. I have done a clean install and removed all other plugins to try to isolate the issue with no success.

## System Versions
* VS Code 1.20.0-insider
* Windows 10 x64
* Flow Extension 0.7.3

## Stacktrace
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'glob'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.Y.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:787)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\trjst\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.7.3\node_modules\rimraf\rimraf.js:7:12)
	at Object.<anonymous> (C:\Users\trjst\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.7.3\node_modules\rimraf\rimraf.js:365:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32) (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:293:155)
```
## Screenshot
![image](https://user-images.githubusercontent.com/3050392/34903389-3e63f4e2-f87c-11e7-8859-378100ab7826.png)

**Comment by orta** [comment]
It'd be great for people coming after you to know what you did to make it work?

**Comment by trjstewart** [comment]
From memory it seemed to be an issue with the Insiders build, I think I switched to stable and it was all good there.
