### ISSUE TITLE
Activating extension `flowtype.flow-for-vscode` failed:  Cannot read property 'assign' of undefined

### ISSUE THREAD

**Issue by DuncanWalter** [flowtype/flow-for-vscode#247]
I've got a project (linked at the bottom) that I've been using this extension to make for the past few months. This morning, I noticed the extension had stopped giving warnings and did not show a status in the status bar anymore. I've tried updating flow-bin, using flow-bin from modules and globally, updating npm, and (as always) lots of restarting. I've reinstalled the extension a couple times as well- no luck. I've had this happen once before, but that time I couldn't get flow to run over my project because I had a bad flowconfig file. This time, flow runs fine- the extension can't start properly for some other reason. Looking in the dev tools of Code, I see:

```
[Extension Host] Activating extension `flowtype.flow-for-vscode` failed:  Cannot read property 'assign' of undefined
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:263
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'assign' of undefined
	at getAssign (/home/duncan/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/util/assign.js:22:23)
	at Object.<anonymous> (/home/duncan/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/util/assign.js:25:18)
	at Object.<anonymous> (/home/duncan/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/util/assign.js:27:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/duncan/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/observable/dom/WebSocketSubject.js:15:16)
	at Object.<anonymous> (/home/duncan/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/observable/dom/WebSocketSubject.js:251:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
```
eventually followed by

```
console.ts:136 [Extension Host] No editors associated with document: /home/duncan/Projects/modular/.vscode/settings.json
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

These errors stay the same no matter how I configure the extension, as far as I can tell. I did update Code recently to version 1.23.1-1525968403. I'm running Ubuntu 18, in case that's relevant. Hopefully this is just some bad configuring on my part?

Thanks,
Duncan Walter

Repo:
https://github.com/DuncanWalter/card-engine

**Comment by browne0** [comment]
I am seeing the same issue here as well! It's been very infuriating 😞

**Comment by betaorbust** [comment]
I'm also seeing this in an almost completely empty test case.
![image](https://user-images.githubusercontent.com/921683/40395082-39cbffdc-5ddb-11e8-9e98-baeb976e96e1.png)

**Comment by betaorbust** [comment]
Oh, snap, that was it.
Looks like somebody blew away the `window` object.
Yoiks...

**Comment by madiodio** [comment]
@betaorbust exactly what I was thinking

**Comment by browne0** [comment]
@madiodio That was the exact issue i had! glad an issue was opened there. Gonna unfollow this and follow that issue 👍

**Comment by DuncanWalter** [comment]
Yeah, that got mine working too. Awesome- thanks guys!
