### ISSUE TITLE
Activating extension 'flowtype.flow-for-vscode' failed: Cannot read property 'assign' of undefined.

### ISSUE THREAD

**Issue by jlpiedrahita** [flowtype/flow-for-vscode#248]
Hello there!

I'm having a hard time trying to figure out why the extension isn't working for me anymore. I went digging down the rabbit hole and ended up getting this log message from the devtools:

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Activating extension `flowtype.flow-for-vscode` failed:  Cannot read property 'assign' of undefined
```

With the following stack trace:

```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'assign' of undefined
    at getAssign (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/util/assign.js:22:23)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/util/assign.js:25:18)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/util/assign.js:27:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/observable/dom/WebSocketSubject.js:15:16)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/observable/dom/WebSocketSubject.js:251:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/observable/dom/webSocket.js:2:26)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/observable/dom/webSocket.js:5:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/add/observable/dom/webSocket.js:3:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/add/observable/dom/webSocket.js:6:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/Rx.js:41:1)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/rxjs/Rx.js:230:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/commons-node/stream.js:38:13)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/commons-node/stream.js:305:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/commons-node/process.js:254:15)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/commons-node/process.js:746:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/FlowHelpers.js:207:16)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/FlowHelpers.js:423:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/utils/util.js:76:20)
    at Object.<anonymous> (/Users/jlpiedrahita/.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/utils/util.js:146:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
```

Setup:
- Mac: 10.13.3 (High Sierra) 
- Node: v8.11.2
- VSCode: 1.23.1
- Flow-for-vscode: 0.8.1

Any ideas of what's going wrong?

Thanks in advance!

**Comment by jlpiedrahita** [comment]
_Update_: I lie a little bit, my Node version was **v8.9.4** (I hadn't restarted VS) and after updating it to **v8.11.2** things started to work correctly.

**Comment by jlpiedrahita** [comment]
Ok, so It has nothing to do with Node (was just a coincidence), closing... thanks!
