### ISSUE TITLE
flow cannot start: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by macrozone** [flowtype/flow-for-vscode#259]
I get this error in vscode console.log:

```console.ts:136 [Extension Host] TypeError: Cannot read property 'map' of undefined
	at newFlowStatusOutputToDiagnostics (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/diagnosticsParser.js:85:24)
	at flowStatusOutputToDiagnostics (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/diagnosticsParser.js:23:12)
	at FlowRoot._callee2$ (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/FlowRoot.js:246:104)
	at tryCatch (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/regenerator-runtime/runtime.js:63:40)
	at Generator.invoke [as _invoke] (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/regenerator-runtime/runtime.js:337:22)
	at Generator.prototype.(anonymous function) [as throw] (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/regenerator-runtime/runtime.js:96:21)
	at step (/path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/FlowRoot.js:39:191)
	at /path/to.vscode/extensions/flowtype.flow-for-vscode-0.8.1/build/pkg/flow-base/lib/FlowRoot.js:39:402
	at <anonymous>
```

vscode-flow version: 0.8.1

flow version: 0.74.0

**Comment by macrozone** [comment]
duplicate of https://github.com/flowtype/flow-for-vscode/issues/255
